//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienRamade.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPassword(string functie, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPasswordAsync(string functie, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersonalInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPersonalInfo(string functie, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersonalInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPersonalInfoAsync(string functie, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterii", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getMaterii();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterii", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getMateriiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGrades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getGrades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGrades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getGradesAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (With_x0020_parametter) of message With_x0020_parametter does not match the default value (getGradesByUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/With parametter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienRamade.ServiceReference1.Withparametter1 getGradesByUser(ClienRamade.ServiceReference1.Withparametter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/With parametter", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienRamade.ServiceReference1.Withparametter1> getGradesByUserAsync(ClienRamade.ServiceReference1.Withparametter request);
        
        // CODEGEN: Generating message contract since the wrapper name (With_x0020_parametters) of message With_x0020_parametters does not match the default value (getGradesByUserAndMaaterie)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/With parametters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienRamade.ServiceReference1.Withparametters1 getGradesByUserAndMaaterie(ClienRamade.ServiceReference1.Withparametters request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/With parametters", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienRamade.ServiceReference1.Withparametters1> getGradesByUserAndMaaterieAsync(ClienRamade.ServiceReference1.Withparametters request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAbsente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAbsente(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAbsente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAbsenteAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertGrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertGrade(string user_profesor, string user_elev, string nume_materie, int nota, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertGrade", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertGradeAsync(string user_profesor, string user_elev, string nume_materie, int nota, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAbsenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertAbsenta(string user_elev, string nume_materie, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAbsenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertAbsentaAsync(string user_elev, string nume_materie, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/motivateAbsenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int motivateAbsenta(int id_absenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/motivateAbsenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> motivateAbsentaAsync(int id_absenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMateriiByProfUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getMateriiByProfUser(string user_profesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMateriiByProfUser", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getMateriiByProfUserAsync(string user_profesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAbsenteByMaterie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAbsenteByMaterie(string nume_materie, string user_elev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAbsenteByMaterie", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAbsenteByMaterieAsync(string nume_materie, string user_elev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getClase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClase", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getClaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEleviByClasa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getEleviByClasa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEleviByClasa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getEleviByClasaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertElev", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertElev(string nume, string data_nasterii, string user_elev, string password, int id_clasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertElev", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertElevAsync(string nume, string data_nasterii, string user_elev, string password, int id_clasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProfesor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertProfesor(string nume, string user_profesor, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertProfesorAsync(string nume, string user_profesor, string password);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="With parametter", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Withparametter {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string user;
        
        public Withparametter() {
        }
        
        public Withparametter(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="With parametterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Withparametter1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("With parametterResult")]
        public System.Data.DataSet WithparametterResult;
        
        public Withparametter1() {
        }
        
        public Withparametter1(System.Data.DataSet WithparametterResult) {
            this.WithparametterResult = WithparametterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="With parametters", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Withparametters {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string materie;
        
        public Withparametters() {
        }
        
        public Withparametters(string user, string materie) {
            this.user = user;
            this.materie = materie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="With paramettersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Withparametters1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("With paramettersResult")]
        public System.Data.DataSet WithparamettersResult;
        
        public Withparametters1() {
        }
        
        public Withparametters1(System.Data.DataSet WithparamettersResult) {
            this.WithparamettersResult = WithparamettersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ClienRamade.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ClienRamade.ServiceReference1.WebServiceSoap>, ClienRamade.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet getPassword(string functie, string user) {
            return base.Channel.getPassword(functie, user);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPasswordAsync(string functie, string user) {
            return base.Channel.getPasswordAsync(functie, user);
        }
        
        public System.Data.DataSet getPersonalInfo(string functie, string user) {
            return base.Channel.getPersonalInfo(functie, user);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPersonalInfoAsync(string functie, string user) {
            return base.Channel.getPersonalInfoAsync(functie, user);
        }
        
        public System.Data.DataSet getMaterii() {
            return base.Channel.getMaterii();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getMateriiAsync() {
            return base.Channel.getMateriiAsync();
        }
        
        public System.Data.DataSet getGrades() {
            return base.Channel.getGrades();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getGradesAsync() {
            return base.Channel.getGradesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienRamade.ServiceReference1.Withparametter1 ClienRamade.ServiceReference1.WebServiceSoap.getGradesByUser(ClienRamade.ServiceReference1.Withparametter request) {
            return base.Channel.getGradesByUser(request);
        }
        
        public System.Data.DataSet getGradesByUser(string user) {
            ClienRamade.ServiceReference1.Withparametter inValue = new ClienRamade.ServiceReference1.Withparametter();
            inValue.user = user;
            ClienRamade.ServiceReference1.Withparametter1 retVal = ((ClienRamade.ServiceReference1.WebServiceSoap)(this)).getGradesByUser(inValue);
            return retVal.WithparametterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienRamade.ServiceReference1.Withparametter1> ClienRamade.ServiceReference1.WebServiceSoap.getGradesByUserAsync(ClienRamade.ServiceReference1.Withparametter request) {
            return base.Channel.getGradesByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienRamade.ServiceReference1.Withparametter1> getGradesByUserAsync(string user) {
            ClienRamade.ServiceReference1.Withparametter inValue = new ClienRamade.ServiceReference1.Withparametter();
            inValue.user = user;
            return ((ClienRamade.ServiceReference1.WebServiceSoap)(this)).getGradesByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienRamade.ServiceReference1.Withparametters1 ClienRamade.ServiceReference1.WebServiceSoap.getGradesByUserAndMaaterie(ClienRamade.ServiceReference1.Withparametters request) {
            return base.Channel.getGradesByUserAndMaaterie(request);
        }
        
        public System.Data.DataSet getGradesByUserAndMaaterie(string user, string materie) {
            ClienRamade.ServiceReference1.Withparametters inValue = new ClienRamade.ServiceReference1.Withparametters();
            inValue.user = user;
            inValue.materie = materie;
            ClienRamade.ServiceReference1.Withparametters1 retVal = ((ClienRamade.ServiceReference1.WebServiceSoap)(this)).getGradesByUserAndMaaterie(inValue);
            return retVal.WithparamettersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienRamade.ServiceReference1.Withparametters1> ClienRamade.ServiceReference1.WebServiceSoap.getGradesByUserAndMaaterieAsync(ClienRamade.ServiceReference1.Withparametters request) {
            return base.Channel.getGradesByUserAndMaaterieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienRamade.ServiceReference1.Withparametters1> getGradesByUserAndMaaterieAsync(string user, string materie) {
            ClienRamade.ServiceReference1.Withparametters inValue = new ClienRamade.ServiceReference1.Withparametters();
            inValue.user = user;
            inValue.materie = materie;
            return ((ClienRamade.ServiceReference1.WebServiceSoap)(this)).getGradesByUserAndMaaterieAsync(inValue);
        }
        
        public System.Data.DataSet getAbsente(string user) {
            return base.Channel.getAbsente(user);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAbsenteAsync(string user) {
            return base.Channel.getAbsenteAsync(user);
        }
        
        public int insertGrade(string user_profesor, string user_elev, string nume_materie, int nota, string data) {
            return base.Channel.insertGrade(user_profesor, user_elev, nume_materie, nota, data);
        }
        
        public System.Threading.Tasks.Task<int> insertGradeAsync(string user_profesor, string user_elev, string nume_materie, int nota, string data) {
            return base.Channel.insertGradeAsync(user_profesor, user_elev, nume_materie, nota, data);
        }
        
        public int insertAbsenta(string user_elev, string nume_materie, string data) {
            return base.Channel.insertAbsenta(user_elev, nume_materie, data);
        }
        
        public System.Threading.Tasks.Task<int> insertAbsentaAsync(string user_elev, string nume_materie, string data) {
            return base.Channel.insertAbsentaAsync(user_elev, nume_materie, data);
        }
        
        public int motivateAbsenta(int id_absenta) {
            return base.Channel.motivateAbsenta(id_absenta);
        }
        
        public System.Threading.Tasks.Task<int> motivateAbsentaAsync(int id_absenta) {
            return base.Channel.motivateAbsentaAsync(id_absenta);
        }
        
        public System.Data.DataSet getMateriiByProfUser(string user_profesor) {
            return base.Channel.getMateriiByProfUser(user_profesor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getMateriiByProfUserAsync(string user_profesor) {
            return base.Channel.getMateriiByProfUserAsync(user_profesor);
        }
        
        public System.Data.DataSet getAbsenteByMaterie(string nume_materie, string user_elev) {
            return base.Channel.getAbsenteByMaterie(nume_materie, user_elev);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAbsenteByMaterieAsync(string nume_materie, string user_elev) {
            return base.Channel.getAbsenteByMaterieAsync(nume_materie, user_elev);
        }
        
        public System.Data.DataSet getClase() {
            return base.Channel.getClase();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getClaseAsync() {
            return base.Channel.getClaseAsync();
        }
        
        public System.Data.DataSet getEleviByClasa(int id) {
            return base.Channel.getEleviByClasa(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getEleviByClasaAsync(int id) {
            return base.Channel.getEleviByClasaAsync(id);
        }
        
        public int insertElev(string nume, string data_nasterii, string user_elev, string password, int id_clasa) {
            return base.Channel.insertElev(nume, data_nasterii, user_elev, password, id_clasa);
        }
        
        public System.Threading.Tasks.Task<int> insertElevAsync(string nume, string data_nasterii, string user_elev, string password, int id_clasa) {
            return base.Channel.insertElevAsync(nume, data_nasterii, user_elev, password, id_clasa);
        }
        
        public int insertProfesor(string nume, string user_profesor, string password) {
            return base.Channel.insertProfesor(nume, user_profesor, password);
        }
        
        public System.Threading.Tasks.Task<int> insertProfesorAsync(string nume, string user_profesor, string password) {
            return base.Channel.insertProfesorAsync(nume, user_profesor, password);
        }
    }
}
